# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *

from images import create_rc
from images import home_rc
from images import menu_rc
from images import testList_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 500)
        MainWindow.setMinimumSize(QSize(1000, 500))
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QSize(1000, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QSize(70, 40))
        self.frame_toggle.setStyleSheet("")
        self.frame_toggle.setFrameShape(QFrame.NoFrame)
        self.frame_toggle.setFrameShadow(QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_toggle = QPushButton(self.frame_toggle)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle.sizePolicy().hasHeightForWidth())
        self.btn_toggle.setSizePolicy(sizePolicy)
        self.btn_toggle.setStyleSheet("background-image: url(:/newPrefix/menu.png);\n"
                                      "background-position: center;\n"
                                      "background-repeat: no-reperat;\n"
                                      "border: none;\n"
                                      "background-color: rgb(27, 29, 35);")
        self.btn_toggle.setText("")
        self.btn_toggle.setObjectName("btn_toggle")
        self.verticalLayout_2.addWidget(self.btn_toggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QFrame(self.Top_Bar)
        self.frame_top.setFrameShape(QFrame.NoFrame)
        self.frame_top.setFrameShadow(QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QFrame(self.centralwidget)
        self.Content.setFrameShape(QFrame.NoFrame)
        self.Content.setFrameShadow(QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_menu_home = QPushButton(self.frame_top_menus)
        self.btn_menu_home.setMinimumSize(QSize(0, 40))
        self.btn_menu_home.setStyleSheet("QPushButton{\n"
                                         "    color:rgb(255, 255, 255);\n"
                                         "    background-color: rgb(35, 35, 35);\n"
                                         "    border: 0px solid;\n"
                                         "    background-image: url(:/newPrefix/home.png);\n"
                                         "    background-repeat: no-reperat;\n"
                                         "    border: none;\n"
                                         "    background-position: center;\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover{\n"
                                         "    background-color: rgb(255, 204, 0);\n"
                                         "}")
        self.btn_menu_home.setText("")
        self.btn_menu_home.setObjectName("btn_menu_home")
        self.verticalLayout_4.addWidget(self.btn_menu_home)
        self.btn_menu_home_2 = QPushButton(self.frame_top_menus)
        self.btn_menu_home_2.setMinimumSize(QSize(0, 40))
        self.btn_menu_home_2.setStyleSheet("QPushButton{\n"
                                           "    color:rgb(255, 255, 255);\n"
                                           "    background-color: rgb(35, 35, 35);\n"
                                           "    border: 0px solid;\n"
                                           "    background-image: url(:/newPrefix/create.png);\n"
                                           "    background-repeat: no-reperat;\n"
                                           "    border: none;\n"
                                           "    background-position: center;\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:hover{\n"
                                           "        \n"
                                           "    background-color: rgb(255, 204, 0);\n"
                                           "}")
        self.btn_menu_home_2.setText("")
        self.btn_menu_home_2.setObjectName("btn_menu_home_2")
        self.verticalLayout_4.addWidget(self.btn_menu_home_2)
        self.btn_menu_home_3 = QPushButton(self.frame_top_menus)
        self.btn_menu_home_3.setMinimumSize(QSize(0, 40))
        self.btn_menu_home_3.setStyleSheet("QPushButton{\n"
                                           "    color:rgb(255, 255, 255);\n"
                                           "    background-color: rgb(35, 35, 35);\n"
                                           "    \n"
                                           "    background-image: url(:/newPrefix/testList.png);\n"
                                           "    background-repeat: no-reperat;\n"
                                           "    border: none;\n"
                                           "    background-position: center;\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:hover{\n"
                                           "        \n"
                                           "    background-color: rgb(255, 204, 0);\n"
                                           "}")
        self.btn_menu_home_3.setText("")
        self.btn_menu_home_3.setObjectName("btn_menu_home_3")
        self.verticalLayout_4.addWidget(self.btn_menu_home_3)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QFrame(self.Content)
        self.frame_pages.setMaximumSize(QSize(16777215, 16777215))
        self.frame_pages.setFrameShape(QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pages_widget = QStackedWidget(self.frame_pages)
        self.pages_widget.setObjectName("pages_widget")
        self.pg_home = QWidget()
        self.pg_home.setObjectName("pg_home")
        self.horizontalLayout_3 = QHBoxLayout(self.pg_home)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QFrame(self.pg_home)
        self.frame.setMaximumSize(QSize(700, 350))
        self.frame.setStyleSheet("QFrame{\n"
                                 "    background-color: rgb(56, 58, 89 );\n"
                                 "    color:rgb(220,    220, 220);\n"
                                 "    border-radius:10px;\n"
                                 "}\n"
                                 "\n"
                                 "")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QVBoxLayout(self.frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QLabel(self.frame)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(90)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 204, 0);")
        self.label.setScaledContents(False)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.label_2 = QLabel(self.frame)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(23)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(98,114,164);")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.horizontalLayout_3.addWidget(self.frame)
        self.pages_widget.addWidget(self.pg_home)
        self.pg_create = QWidget()
        self.pg_create.setObjectName("pg_create")
        self.label_3 = QLabel(self.pg_create)
        self.label_3.setGeometry(QRect(320, 120, 211, 131))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.pages_widget.addWidget(self.pg_create)
        self.pg_list = QWidget()
        self.pg_list.setObjectName("pg_list")
        self.label_4 = QLabel(self.pg_list)
        self.label_4.setGeometry(QRect(330, 130, 211, 131))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.pages_widget.addWidget(self.pg_list)
        self.verticalLayout_5.addWidget(self.pages_widget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages_widget.setCurrentIndex(2)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "EzTests"))
        self.label_2.setText(_translate("MainWindow", "Genera Test de manera sencilla"))
        self.label_3.setText(_translate("MainWindow", "Pagina de creacion"))
        self.label_4.setText(_translate("MainWindow", "Pagina de test"))
