# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from images import res


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(140, 20, 550, 500))
        self.widget.setObjectName("widget")
        self.label_image = QtWidgets.QLabel(self.widget)
        self.label_image.setGeometry(QtCore.QRect(40, 30, 280, 430))
        self.label_image.setStyleSheet("border-image: url(:/image/pexels-james-wheeler.jpg);\n"
                                       "border-top-left-radius: 50px;")
        self.label_image.setText("")
        self.label_image.setScaledContents(True)
        self.label_image.setObjectName("label_image")
        self.label_shadowBacground = QtWidgets.QLabel(self.widget)
        self.label_shadowBacground.setGeometry(QtCore.QRect(40, 30, 280, 430))
        self.label_shadowBacground.setStyleSheet("background-color:rgba(0,0,0,20);\n"
                                                 "border-top-left-radius: 50px;")
        self.label_shadowBacground.setText("")
        self.label_shadowBacground.setObjectName("label_shadowBacground")
        self.label_witheShadow = QtWidgets.QLabel(self.widget)
        self.label_witheShadow.setGeometry(QtCore.QRect(270, 30, 240, 430))
        self.label_witheShadow.setStyleSheet("background-color:rgba(255,255,255,255);\n"
                                             "border-bottom-right-radius: 50px;")
        self.label_witheShadow.setText("")
        self.label_witheShadow.setObjectName("label_witheShadow")
        self.label_loginIn = QtWidgets.QLabel(self.widget)
        self.label_loginIn.setGeometry(QtCore.QRect(300, 110, 188, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_loginIn.setFont(font)
        self.label_loginIn.setStyleSheet("color: rgba(0,0,0,200);")
        self.label_loginIn.setAlignment(QtCore.Qt.AlignCenter)
        self.label_loginIn.setObjectName("label_loginIn")
        self.lineEdit_name = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_name.setGeometry(QtCore.QRect(297, 180, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                         "border:none;\n"
                                         "border-bottom: 2px solid rgba( 46, 82, 101, 200);\n"
                                         "color: rgba(0, 0, 0, 240);\n"
                                         "padding-bottom: 7px;")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_password = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_password.setGeometry(QtCore.QRect(297, 245, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                             "border:none;\n"
                                             "border-bottom: 2px solid rgba( 46, 82, 101, 200);\n"
                                             "color: rgba(0, 0, 0, 240);\n"
                                             "padding-bottom: 7px;")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_logIn = QtWidgets.QPushButton(self.widget)
        self.pushButton_logIn.setGeometry(QtCore.QRect(297, 340, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_logIn.setFont(font)
        self.pushButton_logIn.setStyleSheet("QPushButton{\n"
                                            "    background-color: qlineargradient(spread:pad, x1:0, y1:0.523, x2:1, y2:0.522, stop:0.625 rgba(132, 250, 176, 255), stop:1 rgba(143, 211, 244, 255));\n"
                                            "    border-radius: 5px\n"
                                            "}\n"
                                            "QPushButton::hover{\n"
                                            "    background-color: qlineargradient(spread:repeat, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(143, 211, 244, 255), stop:0.477273 rgba(135, 255, 180, 255));\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton::pressed{\n"
                                            "    padding-lef: 5px;\n"
                                            "    padding-top:5px;\n"
                                            "    background-color: rgb(97, 255, 211);\n"
                                            "}\n"
                                            "")
        self.pushButton_logIn.setObjectName("pushButton_logIn")
        self.label_shadowTittle = QtWidgets.QLabel(self.widget)
        self.label_shadowTittle.setGeometry(QtCore.QRect(40, 80, 230, 111))
        self.label_shadowTittle.setStyleSheet("background-color: rgba(0, 0, 0, 75);")
        self.label_shadowTittle.setText("")
        self.label_shadowTittle.setObjectName("label_shadowTittle")
        self.label_tittle = QtWidgets.QLabel(self.widget)
        self.label_tittle.setGeometry(QtCore.QRect(64, 103, 180, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_tittle.setFont(font)
        self.label_tittle.setStyleSheet("color: rgba(255,255,255,210);")
        self.label_tittle.setObjectName("label_tittle")
        self.label_aviso = QtWidgets.QLabel(self.widget)
        self.label_aviso.setGeometry(QtCore.QRect(300, 300, 192, 21))
        self.label_aviso.setStyleSheet("color:rgba(0,0,0,210)")
        self.label_aviso.setText("")
        self.label_aviso.setAlignment(QtCore.Qt.AlignCenter)
        self.label_aviso.setObjectName("label_aviso")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_loginIn.setText(_translate("MainWindow", "Registro"))
        self.lineEdit_name.setPlaceholderText(_translate("MainWindow", "Nombre de Usuario"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "Constraseña"))
        self.pushButton_logIn.setText(_translate("MainWindow", "Registrarse"))
        self.label_tittle.setText(_translate("MainWindow", "EzTest \n"
                                                           "Generator"))
